Repository zero-one-group/geni, pull requests merged in 2023-11, with the labels that each got.

#349 Exclude `abs` in `src/clojure/zero_one/geni/core/functions.clj`
  src/clojure/zero_one/geni/core/functions.clj
Labels: enhancement

#351 Fix CI badge
  README.md
Labels: documentation

#352 Fix `already refers` warnings in Clojure 1.11
  docker/project.clj
  project.clj
Labels: enhancement

#343 Fix code for Cookbook 11.3
  docs/cookbook/cookbook-11.clj
  docs/cookbook/part_11_basic_ml_pipelines.md
Labels: documentation, good first issue

#353 Update dependencies in README.md
  README.md
Labels: documentation
